import logging
import os
import os.path as osp
import glob
import json
import torch

# from torch.cuda.amp import autocast, GradScaler
import mmcv
import time
import cv2
import numpy as np
from collections import OrderedDict

from detectron2.utils.events import EventStorage
from detectron2.checkpoint import PeriodicCheckpointer
from detectron2.evaluation import (
    CityscapesInstanceEvaluator,
    CityscapesSemSegEvaluator,
    COCOEvaluator,
    COCOPanopticEvaluator,
    DatasetEvaluators,
    LVISEvaluator,
    PascalVOCDetectionEvaluator,
    SemSegEvaluator,
)

from detectron2.data.common import AspectRatioGroupedDataset
from detectron2.data import MetadataCatalog
from pytorch_lightning.lite import LightningLite  # import LightningLite

from lib.utils.setup_logger import log_first_n
from lib.utils.utils import dprint
from lib.vis_utils.image import grid_show, vis_bbox_opencv
from lib.torch_utils.torch_utils import ModelEMA
from lib.torch_utils.misc import nan_to_num
from core.utils import solver_utils
import core.utils.my_comm as comm
from core.utils.my_checkpoint import MyCheckpointer
from core.utils.my_writer import (
    EpochJSONWriter,
    MyCommonMetricPrinter,
    MyJSONWriter,
    MyTensorboardXWriter,
)
from core.utils.utils import get_emb_show
from core.utils.data_utils import denormalize_image
from core.gdrn_modeling.datasets.data_loader import build_gdrn_train_loader, build_gdrn_test_loader

from .engine_utils import batch_data, get_out_coor, get_out_mask
from .gdrn_evaluator import gdrn_inference_on_dataset, GDRN_Evaluator, gdrn_save_result_of_dataset
from .gdrn_custom_evaluator import GDRN_EvaluatorCustom
from .artifact_layout import (
    artifact_dir,
    compact_log_enabled,
    evaluation_dir,
    structured_layout_enabled,
    tensorboard_enabled,
)
import ref


logger = logging.getLogger(__name__)


def load_bop_selection_metrics(eval_out_dir):
    """Load BOP AR and ADD(-S)@0.1d generated by the official evaluator."""

    score_paths = sorted(glob.glob(osp.join(eval_out_dir, "*", "scores_bop19.json")))
    if len(score_paths) != 1:
        logger.warning("Expected one scores_bop19.json under %s, found %d", eval_out_dir, len(score_paths))
        return {}

    with open(score_paths[0], "r") as handle:
        bop_scores = json.load(handle)
    metrics = {"bop_ar": float(bop_scores["bop19_average_recall"])}

    result_dir = osp.dirname(score_paths[0])
    add_paths = []
    for directory_pattern in ("error=ad_ntop=*", "error:ad_ntop:*"):
        for score_name in (
            "scores_th=0.100_min-visib=-1.000.json",
            "scores_th:0.100_min-visib:-1.000.json",
        ):
            add_paths.extend(
                glob.glob(osp.join(result_dir, directory_pattern, score_name))
            )
    add_paths = sorted(set(add_paths))
    if len(add_paths) == 1:
        with open(add_paths[0], "r") as handle:
            add_scores = json.load(handle)
        metrics["add_s_0.1d"] = float(add_scores["recall"])
        metrics["add_s_obj_recalls"] = add_scores.get("obj_recalls", {})
    else:
        logger.warning("Expected one ADD(-S)@0.1d score under %s, found %d", result_dir, len(add_paths))
    return metrics


def is_better_checkpoint(candidate, incumbent, tie_tolerance=0.001):
    """Compare metric dictionaries using BOP AR first and ADD(-S) second."""

    if not incumbent:
        return True
    candidate_primary = float(candidate["bop_ar"])
    incumbent_primary = float(incumbent["bop_ar"])
    if candidate_primary > incumbent_primary + tie_tolerance:
        return True
    if abs(candidate_primary - incumbent_primary) <= tie_tolerance:
        return float(candidate.get("add_s_0.1d", float("-inf"))) > float(
            incumbent.get("add_s_0.1d", float("-inf"))
        )
    return False


def should_evaluate_epoch(iteration, iterations_per_epoch, eval_period):
    """Return True only after a requested epoch has fully completed."""

    if int(eval_period) <= 0:
        return False
    completed = int(iteration) + 1
    if completed % int(iterations_per_epoch) != 0:
        return False
    epoch = completed // int(iterations_per_epoch)
    return epoch % int(eval_period) == 0


class GDRN_Lite(LightningLite):
    def get_evaluator(self, cfg, dataset_name, output_folder=None):
        """Create evaluator(s) for a given dataset.

        This uses the special metadata "evaluator_type" associated with
        each builtin dataset. For your own dataset, you can simply
        create an evaluator manually in your script and do not have to
        worry about the hacky if-else logic here.
        """
        if output_folder is None:
            output_folder = osp.join(cfg.OUTPUT_DIR, "inference")
        evaluator_list = []
        evaluator_type = MetadataCatalog.get(dataset_name).evaluator_type
        if evaluator_type in ["sem_seg", "coco_panoptic_seg"]:
            evaluator_list.append(
                SemSegEvaluator(
                    dataset_name,
                    distributed=True,
                    num_classes=cfg.MODEL.SEM_SEG_HEAD.NUM_CLASSES,
                    ignore_label=cfg.MODEL.SEM_SEG_HEAD.IGNORE_VALUE,
                    output_dir=output_folder,
                )
            )
        if evaluator_type in ["coco", "coco_panoptic_seg"]:
            evaluator_list.append(COCOEvaluator(dataset_name, cfg, True, output_folder))
        if evaluator_type == "coco_panoptic_seg":
            evaluator_list.append(COCOPanopticEvaluator(dataset_name, output_folder))
        if evaluator_type == "cityscapes_instance":
            assert (
                torch.cuda.device_count() >= self.global_rank
            ), "CityscapesEvaluator currently do not work with multiple machines."
            return CityscapesInstanceEvaluator(dataset_name)
        if evaluator_type == "cityscapes_sem_seg":
            assert (
                torch.cuda.device_count() >= self.global_rank
            ), "CityscapesEvaluator currently do not work with multiple machines."
            return CityscapesSemSegEvaluator(dataset_name)
        if evaluator_type == "pascal_voc":
            return PascalVOCDetectionEvaluator(dataset_name)
        if evaluator_type == "lvis":
            return LVISEvaluator(dataset_name, cfg, True, output_folder)

        _distributed = self.world_size > 1
        dataset_meta = MetadataCatalog.get(cfg.DATASETS.TRAIN[0])
        train_obj_names = dataset_meta.objs
        if evaluator_type == "bop":
            gdrn_eval_cls = GDRN_Evaluator if cfg.VAL.get("USE_BOP", False) else GDRN_EvaluatorCustom
            return gdrn_eval_cls(
                cfg, dataset_name, distributed=_distributed, output_dir=output_folder, train_objs=train_obj_names
            )

        if len(evaluator_list) == 0:
            raise NotImplementedError(
                "no Evaluator for the dataset {} with the type {}".format(dataset_name, evaluator_type)
            )
        if len(evaluator_list) == 1:
            return evaluator_list[0]
        return DatasetEvaluators(evaluator_list)

    def get_tbx_event_writer(self, out_dir, backup=False):
        tb_logdir = osp.join(out_dir, "tb")
        mmcv.mkdir_or_exist(tb_logdir)
        if backup and self.is_global_zero:
            old_tb_logdir = osp.join(out_dir, "tb_old")
            mmcv.mkdir_or_exist(old_tb_logdir)
            os.system("mv -v {} {}".format(osp.join(tb_logdir, "events.*"), old_tb_logdir))

        tbx_event_writer = MyTensorboardXWriter(tb_logdir, backend="tensorboardX")
        return tbx_event_writer

    def do_save_results(self, cfg, model, epoch=None, iteration=None):
        dataset_meta = MetadataCatalog.get(cfg.DATASETS.TRAIN[0])
        train_obj_names = dataset_meta.objs

        for dataset_name in cfg.DATASETS.TEST:
            save_out_dir = evaluation_dir(
                cfg,
                dataset_name,
                epoch=epoch,
                iteration=iteration,
            )

            data_loader = build_gdrn_test_loader(cfg, dataset_name, train_objs=train_obj_names)
            data_loader = self.setup_dataloaders(data_loader, replace_sampler=False, move_to_device=False)

            gdrn_save_result_of_dataset(
                cfg,
                model,
                data_loader,
                output_dir=save_out_dir,
                dataset_name=dataset_name,
                train_objs=train_obj_names,
                amp_test=cfg.TEST.AMP_TEST,
            )

    def do_test(self, cfg, model, epoch=None, iteration=None):
        results = OrderedDict()
        for dataset_name in cfg.DATASETS.TEST:
            eval_out_dir = evaluation_dir(
                cfg,
                dataset_name,
                epoch=epoch,
                iteration=iteration,
            )
            evaluator = self.get_evaluator(cfg, dataset_name, eval_out_dir)
            evaluator.lite_self = self
            data_loader = build_gdrn_test_loader(cfg, dataset_name, train_objs=evaluator.train_objs)
            data_loader = self.setup_dataloaders(data_loader, replace_sampler=False, move_to_device=False)
            results_i = gdrn_inference_on_dataset(cfg, model, data_loader, evaluator, amp_test=cfg.TEST.AMP_TEST)
            if self.is_global_zero and MetadataCatalog.get(dataset_name).evaluator_type == "bop":
                results_i = dict(results_i)
                results_i.update(load_bop_selection_metrics(eval_out_dir))
                if compact_log_enabled(cfg):
                    compact_metrics = {
                        "epoch": None if epoch is None else int(epoch),
                        "bop_ar": results_i.get("bop_ar"),
                        "add_s_0.1d": results_i.get("add_s_0.1d"),
                        "add_s_obj_recalls": results_i.get("add_s_obj_recalls", {}),
                    }
                    logger.info(
                        "EVAL_SUMMARY %s",
                        json.dumps(compact_metrics, sort_keys=True),
                    )
            results[dataset_name] = results_i

        if len(results) == 1:
            results = list(results.values())[0]
        return results

    def do_train(self, cfg, args, model, optimizer, renderer=None, resume=False):
        model.train()

        # some basic settings =========================
        dataset_meta = MetadataCatalog.get(cfg.DATASETS.TRAIN[0])
        data_ref = ref.__dict__[dataset_meta.ref_key]
        obj_names = dataset_meta.objs

        # load data ===================================
        train_dset_names = cfg.DATASETS.TRAIN
        data_loader = build_gdrn_train_loader(cfg, train_dset_names)

        data_loader_iter = iter(data_loader)

        # load 2nd train dataloader if needed
        train_2_dset_names = cfg.DATASETS.get("TRAIN2", ())
        train_2_ratio = cfg.DATASETS.get("TRAIN2_RATIO", 0.0)
        if train_2_ratio > 0.0 and len(train_2_dset_names) > 0:
            data_loader_2 = build_gdrn_train_loader(cfg, train_2_dset_names)
            data_loader_2_iter = iter(data_loader_2)
        else:
            data_loader_2 = None
            data_loader_2_iter = None

        images_per_batch = cfg.SOLVER.IMS_PER_BATCH
        if isinstance(data_loader, AspectRatioGroupedDataset):
            dataset_len = len(data_loader.dataset.dataset)
            if data_loader_2 is not None and cfg.DATASETS.DATA_LEN_WITH_TRAIN2:
                logger.info("Calculate dataset length with TRAIN2")
                dataset_len += len(data_loader_2.dataset.dataset)
            iters_per_epoch = dataset_len // images_per_batch
        else:
            dataset_len = len(data_loader.dataset)
            if data_loader_2 is not None and cfg.DATASETS.DATA_LEN_WITH_TRAIN2:
                logger.info("Calculate dataset length with TRAIN2")
                dataset_len += len(data_loader_2.dataset)
            iters_per_epoch = dataset_len // images_per_batch
        max_iter = cfg.SOLVER.TOTAL_EPOCHS * iters_per_epoch
        dprint("images_per_batch: ", images_per_batch)
        dprint("dataset length: ", dataset_len)
        dprint("iters per epoch: ", iters_per_epoch)
        dprint("total iters: ", max_iter)

        data_loader = self.setup_dataloaders(data_loader, replace_sampler=False, move_to_device=False)
        if data_loader_2 is not None:
            data_loader_2 = self.setup_dataloaders(data_loader_2, replace_sampler=False, move_to_device=False)

        bs_ref = cfg.SOLVER.get("REFERENCE_BS", cfg.SOLVER.IMS_PER_BATCH)
        accumulate_iter = solver_utils.get_accumulation_steps(bs_ref, cfg.SOLVER.IMS_PER_BATCH)
        # NOTE: update lr every accumulate_iter
        optimizer_updates = solver_utils.optimizer_updates_per_training(
            iters_per_epoch,
            cfg.SOLVER.TOTAL_EPOCHS,
            accumulate_iter,
        )
        scheduler = solver_utils.build_lr_scheduler(cfg, optimizer, total_iters=optimizer_updates)

        # resume or load model ===================================
        extra_ckpt_dict = dict(
            optimizer=optimizer,
            scheduler=scheduler,
        )
        if hasattr(self._precision_plugin, "scaler"):
            extra_ckpt_dict["gradscaler"] = self._precision_plugin.scaler
        checkpoint_dir = artifact_dir(cfg, "checkpoints")
        mmcv.mkdir_or_exist(checkpoint_dir)
        checkpointer = MyCheckpointer(
            model,
            checkpoint_dir,
            save_to_disk=self.is_global_zero,
            prefix_to_remove="_module.",
            **extra_ckpt_dict,
        )
        checkpoint_state = checkpointer.resume_or_load(cfg.MODEL.WEIGHTS, resume=resume)
        start_iter = checkpoint_state.get("iteration", -1) + 1

        # Exponential moving average (NOTE: initialize ema after loading weights) ========================
        if self.is_global_zero and cfg.MODEL.EMA.ENABLED:
            ema = ModelEMA(model, **cfg.MODEL.EMA.INIT_CFG)
            ema.updates = start_iter // accumulate_iter
            # save the ema model
            checkpointer.model = ema.ema.module if hasattr(ema.ema, "module") else ema.ema
        else:
            ema = None

        if cfg.SOLVER.CHECKPOINT_BY_EPOCH:
            ckpt_period = cfg.SOLVER.CHECKPOINT_PERIOD * iters_per_epoch
        else:
            ckpt_period = cfg.SOLVER.CHECKPOINT_PERIOD
        best_cfg = cfg.SOLVER.get("BEST_CHECKPOINT", {})
        keep_best = bool(best_cfg.get("ENABLED", False))
        recent_to_keep = int(cfg.SOLVER.MAX_TO_KEEP) - int(keep_best)
        if recent_to_keep <= 0:
            raise ValueError("MAX_TO_KEEP must leave room for at least one recent checkpoint")
        periodic_checkpointer = PeriodicCheckpointer(
            checkpointer,
            ckpt_period,
            max_iter=None if keep_best else max_iter,
            max_to_keep=recent_to_keep,
        )
        structured_checkpoints = structured_layout_enabled(cfg)
        recent_checkpoint_paths = (
            sorted(glob.glob(osp.join(checkpoint_dir, "model_epoch_*.pth")))
            if structured_checkpoints and resume
            else []
        )
        best_metrics = {}
        best_state_path = osp.join(checkpoint_dir, "best_checkpoint.json")
        if keep_best and resume and osp.exists(best_state_path):
            with open(best_state_path, "r") as handle:
                best_metrics = json.load(handle).get("metrics", {})

        # build writers ==============================================
        train_dir = artifact_dir(cfg, "train")
        mmcv.mkdir_or_exist(train_dir)
        tbx_event_writer = None
        tbx_writer = None
        if tensorboard_enabled(cfg):
            tbx_event_writer = self.get_tbx_event_writer(
                train_dir,
                backup=not cfg.get("RESUME", False),
            )
            tbx_writer = tbx_event_writer._writer
        if self.is_global_zero:
            metrics_name = "metrics.jsonl" if structured_layout_enabled(cfg) else "metrics.json"
            writers = [
                MyCommonMetricPrinter(max_iter),
                MyJSONWriter(osp.join(train_dir, metrics_name)),
            ]
            if structured_layout_enabled(cfg):
                writers.append(
                    EpochJSONWriter(
                        osp.join(train_dir, "epoch_summary.jsonl"),
                        iters_per_epoch,
                    )
                )
            if tbx_event_writer is not None:
                writers.append(tbx_event_writer)
        else:
            writers = []
        self._last_periodic_eval_results = None

        # compared to "train_net.py", we do not support accurate timing and
        # precise BN here, because they are not trivial to implement
        logger.info("Starting training from iteration {}".format(start_iter))
        iter_time = None
        with EventStorage(start_iter) as storage:
            optimizer.zero_grad(set_to_none=True)
            for iteration in range(start_iter, max_iter):
                storage.iter = iteration
                epoch = iteration // iters_per_epoch + 1  # epoch start from 1
                storage.put_scalar("epoch", epoch, smoothing_hint=False)

                if np.random.rand() < train_2_ratio:
                    data = next(data_loader_2_iter)
                else:
                    data = next(data_loader_iter)

                if iter_time is not None:
                    storage.put_scalar("time", time.perf_counter() - iter_time)
                iter_time = time.perf_counter()

                # if cfg.TRAIN.VIS:
                #     vis_train_data(data, obj_names, cfg)

                # forward ============================================================
                batch = batch_data(cfg, data, renderer=renderer)
                if cfg.INPUT.WITH_DEPTH:
                    inp = torch.cat([batch["roi_img"], batch["roi_depth"]], dim=1)
                else:
                    inp = batch["roi_img"]

                out_dict, loss_dict = model(
                    inp,
                    gt_xyz=batch.get("roi_xyz", None),
                    gt_xyz_bin=batch.get("roi_xyz_bin", None),
                    gt_mask_trunc=batch["roi_mask_trunc"],
                    gt_mask_visib=batch["roi_mask_visib"],
                    gt_mask_full=batch.get("roi_mask_full", None),
                    gt_mask_obj=batch.get("roi_mask_obj", None),
                    gt_region=batch.get("roi_region", None),
                    gt_ego_rot=batch.get("ego_rot", None),
                    gt_trans=batch.get("trans", None),
                    gt_trans_ratio=batch["roi_trans_ratio"],
                    gt_points=batch.get("roi_points", None),
                    sym_infos=batch.get("sym_info", None),
                    roi_classes=batch["roi_cls"],
                    roi_cams=batch["roi_cam"],
                    roi_whs=batch["roi_wh"],
                    roi_centers=batch["roi_center"],
                    resize_ratios=batch["resize_ratio"],
                    roi_coord_2d=batch.get("roi_coord_2d", None),
                    roi_coord_2d_rel=batch.get("roi_coord_2d_rel", None),
                    roi_extents=batch.get("roi_extent", None),
                    depth_stats=batch.get("roi_depth_stats", None),
                    do_loss=True,
                )
                losses = sum(loss_dict.values())
                assert torch.isfinite(losses).all(), loss_dict

                if self.is_global_zero:
                    log_first_n(logging.INFO, "iteration {} forward finished.".format(iteration), n=2)

                loss_dict_reduced = {k: v.item() for k, v in comm.reduce_dict(loss_dict).items()}
                losses_reduced = sum(loss for loss in loss_dict_reduced.values())
                if self.is_global_zero:
                    storage.put_scalars(total_loss=losses_reduced, **loss_dict_reduced)

                # backward & optimize ======================================================
                accumulation_divisor = solver_utils.accumulation_window_size(
                    iteration,
                    accumulate_iter,
                    iters_per_epoch,
                )
                self.backward(losses / accumulation_divisor)
                do_optimizer_step = solver_utils.should_optimizer_step(
                    iteration,
                    accumulate_iter,
                    iters_per_epoch,
                    max_iter,
                )
                if do_optimizer_step:
                    if cfg.SOLVER.SET_NAN_GRAD_TO_ZERO:
                        for param in model.parameters():
                            if param.grad is not None:
                                nan_to_num(param.grad, nan=0, posinf=1e5, neginf=-1e5, out=param.grad)
                    optimizer.step()
                    optimizer.zero_grad(set_to_none=True)
                    if ema is not None:
                        ema.update(model)
                    storage.put_scalar("lr", optimizer.param_groups[0]["lr"], smoothing_hint=False)
                    scheduler.step()
                if self.is_global_zero:
                    log_first_n(logging.INFO, "iteration {} backward finished.".format(iteration), n=2)

                if (
                    should_evaluate_epoch(
                        iteration,
                        iters_per_epoch,
                        cfg.TEST.EVAL_PERIOD,
                    )
                ):
                    if ema is not None:
                        ema.update_attr(model)
                        eval_results = self.do_test(
                            cfg,
                            model=ema.ema.module if hasattr(ema.ema, "module") else ema.ema,
                            epoch=epoch,
                            iteration=iteration,
                        )
                    else:
                        eval_results = self.do_test(cfg, model, epoch=epoch, iteration=iteration)
                    if iteration == max_iter - 1:
                        self._last_periodic_eval_results = eval_results
                    if keep_best and self.is_global_zero and eval_results.get("bop_ar") is not None:
                        tie_tolerance = float(best_cfg.get("PRIMARY_TIE_TOL", 0.001))
                        if is_better_checkpoint(eval_results, best_metrics, tie_tolerance=tie_tolerance):
                            best_metrics = {
                                "bop_ar": float(eval_results["bop_ar"]),
                                "add_s_0.1d": float(eval_results.get("add_s_0.1d", float("nan"))),
                            }
                            checkpointer.save(
                                "model_best",
                                iteration=iteration,
                                epoch=epoch,
                                selection_metrics=best_metrics,
                            )
                            with open(best_state_path, "w") as handle:
                                json.dump(
                                    {"epoch": epoch, "iteration": iteration, "metrics": best_metrics},
                                    handle,
                                    indent=2,
                                    sort_keys=True,
                                )
                    # Compared to "train_net.py", the test results are not dumped to EventStorage
                    self.barrier()

                early_verbose = iteration < 100 and not compact_log_enabled(cfg)
                if iteration - start_iter > 5 and (
                    (iteration + 1) % cfg.TRAIN.PRINT_FREQ == 0
                    or (iteration + 1) % iters_per_epoch == 0
                    or iteration == max_iter - 1
                    or early_verbose
                ):
                    for writer in writers:
                        writer.write()
                    # visualize some images ========================================
                    if cfg.TRAIN.VIS_IMG and tbx_writer is not None:
                        with torch.no_grad():
                            vis_i = 0
                            roi_img_vis = batch["roi_img"][vis_i].cpu().numpy()
                            roi_img_vis = denormalize_image(roi_img_vis, cfg).transpose(1, 2, 0).astype("uint8")
                            tbx_writer.add_image("input_image", roi_img_vis, iteration)

                            out_coor_x = out_dict["coor_x"].detach()
                            out_coor_y = out_dict["coor_y"].detach()
                            out_coor_z = out_dict["coor_z"].detach()
                            out_xyz = get_out_coor(cfg, out_coor_x, out_coor_y, out_coor_z)

                            out_xyz_vis = out_xyz[vis_i].cpu().numpy().transpose(1, 2, 0)
                            out_xyz_vis = get_emb_show(out_xyz_vis)
                            tbx_writer.add_image("out_xyz", out_xyz_vis, iteration)

                            gt_xyz_vis = batch["roi_xyz"][vis_i].cpu().numpy().transpose(1, 2, 0)
                            gt_xyz_vis = get_emb_show(gt_xyz_vis)
                            tbx_writer.add_image("gt_xyz", gt_xyz_vis, iteration)

                            out_mask = out_dict["mask"].detach()
                            out_mask = get_out_mask(cfg, out_mask)
                            out_mask_vis = out_mask[vis_i, 0].cpu().numpy()
                            tbx_writer.add_image("out_mask", out_mask_vis, iteration)

                            gt_mask_vis = batch["roi_mask"][vis_i].detach().cpu().numpy()
                            tbx_writer.add_image("gt_mask", gt_mask_vis, iteration)
                checkpoint_due = (iteration + 1) % periodic_checkpointer.period == 0 or (
                    periodic_checkpointer.max_iter is not None
                    and (iteration + 1) >= periodic_checkpointer.max_iter
                )
                if checkpoint_due:
                    if hasattr(optimizer, "consolidate_state_dict"):  # for ddp_sharded
                        optimizer.consolidate_state_dict()
                if structured_checkpoints:
                    if checkpoint_due and self.is_global_zero:
                        checkpoint_name = f"model_epoch_{int(epoch):03d}"
                        checkpointer.save(
                            checkpoint_name,
                            iteration=iteration,
                            epoch=epoch,
                        )
                        checkpoint_path = osp.join(
                            checkpoint_dir,
                            f"{checkpoint_name}.pth",
                        )
                        recent_checkpoint_paths.append(checkpoint_path)
                        while len(recent_checkpoint_paths) > recent_to_keep:
                            old_checkpoint = recent_checkpoint_paths.pop(0)
                            if osp.isfile(old_checkpoint):
                                os.remove(old_checkpoint)
                else:
                    periodic_checkpointer.step(iteration, epoch=epoch)


def vis_train_data(data, obj_names, cfg):
    for i, d in enumerate(data):
        # if i >= 1:
        #     continue
        full_img = mmcv.imread(d["file_name"], "color")
        # if "000009/rgb/000047.png" not in d["file_name"]:
        #     continue
        print(d["file_name"])
        im_H, im_W = full_img.shape[:2]
        roi_cls = d["roi_cls"]
        if roi_cls not in [0]:
            continue
        bbox_center = d["bbox_center"]
        scale = d["scale"]
        x1 = max(min(bbox_center[0] - scale / 2, im_W), 0)
        x2 = max(min(bbox_center[0] + scale / 2, im_W), 0)
        y1 = max(min(bbox_center[1] - scale / 2, im_H), 0)
        y2 = max(min(bbox_center[1] + scale / 2, im_H), 0)
        full_img_vis = vis_bbox_opencv(full_img, np.array([x1, y1, x2, y2]), fmt="xyxy")

        bbox_ori = d["bbox"]
        full_img_bbox = vis_bbox_opencv(full_img, bbox_ori, fmt="xyxy")
        obj_name = obj_names[roi_cls]

        roi_img = d["roi_img"].numpy()
        roi_img = denormalize_image(roi_img, cfg).transpose(1, 2, 0).astype("uint8")

        roi_mask_trunc = d["roi_mask_trunc"].numpy().astype("bool")
        roi_mask_visib = d["roi_mask_visib"].numpy().astype("bool")
        roi_mask_obj = d["roi_mask_obj"].numpy().astype("bool")

        kernel = np.ones((3, 3), np.uint8)
        erode_mask_obj = cv2.erode(roi_mask_obj.astype("uint8"), kernel, iterations=1)

        roi_xyz = d["roi_xyz"].numpy().transpose(1, 2, 0)
        roi_xyz_show = get_emb_show(roi_xyz) * erode_mask_obj[:, :, None].astype("float32")

        coord2d = d["roi_coord_2d"].numpy().transpose(1, 2, 0)
        roi_h, roi_w = coord2d.shape[:2]
        zeros_1 = np.zeros((roi_h, roi_w, 1), dtype="float32")
        coord2d_3 = np.concatenate([zeros_1, get_emb_show(coord2d)], axis=2)

        # yapf: disable
        vis_imgs = [
            full_img_vis[:, :, [2, 1, 0]], full_img_bbox[:, :, [2, 1, 0]], roi_img[:, :, [2, 1, 0]],
            roi_mask_trunc * erode_mask_obj, roi_mask_visib*erode_mask_obj, roi_mask_obj*erode_mask_obj,
            roi_xyz_show,
            coord2d_3,
            coord2d[:, :, 0], coord2d[:, :, 1]
        ]
        titles = [
            "full_img", "ori_bbox", f"roi_img({obj_name})",
            "roi_mask_trunc",  "roi_mask_visib", "roi_mask_obj",
            "roi_xyz",
            "roi_coord2d",
            "roi_coord2d_x", "roi_coord2d_y"
        ]
        row = 3
        col = 4
        if "roi_region" in d:
            roi_region = d["roi_region"].numpy()  # (bh, bw)
            roi_region_3 = np.zeros((roi_h, roi_w, 3), dtype="float32")
            for region_id in range(256):
                # if region_id == 0:
                #     continue
                if region_id in roi_region:
                    for _c in range(3):
                        roi_region_3[:, :, _c][roi_region == region_id] = roi_xyz_show[:, :, _c][roi_region == region_id].mean()
            roi_region_3 = roi_region_3  * erode_mask_obj[:, :, None].astype("float32")
            vis_imgs.append(roi_region_3)
            titles.append("roi_region")
        if len(vis_imgs) > row * col:
            col += 1
        for _im, _name in zip(vis_imgs, titles):
            save_path = osp.join(cfg.OUTPUT_DIR, "vis", _name+'.png')
            mmcv.mkdir_or_exist(osp.dirname(save_path))
            if _im.shape[-1] == 3:
                _im = _im[:, :, [2,1,0]]
            if _im.max() < 1.1:
                _im = (_im * 255).astype("uint8")
            print(save_path)
            mmcv.imwrite(_im, save_path)

        grid_show(vis_imgs, titles, row=row, col=col)

        # yapf: enable
